version: '3.8'

services:
  # Node.js API 서버 (Wiki 중심)
  wiki-api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: wiki_automation_api
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}
      - MAX_FILES_PER_REQUEST=${MAX_FILES_PER_REQUEST}
      - WIKI_BASE_URL=${WIKI_BASE_URL}
      - WIKI_API_TOKEN=${WIKI_API_TOKEN}
      - WIKI_SPACE_KEY=${WIKI_SPACE_KEY}
      - WIKI_USERNAME=${WIKI_USERNAME}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./uploads:/app/uploads
      - ./summaries:/app/summaries
      - ./logs:/app/logs
    networks:
      - wiki_network
    depends_on:
      - redis

  # n8n Wiki 워크플로우
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_wiki_automation
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - GENERIC_TIMEZONE=Asia/Seoul
      - N8N_DEFAULT_LOCALE=ko
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
      # Wiki 관련 변수
      - WIKI_BASE_URL=${WIKI_BASE_URL}
      - WIKI_API_TOKEN=${WIKI_API_TOKEN}
      - WIKI_SPACE_KEY=${WIKI_SPACE_KEY}
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./uploads:/home/node/uploads:ro
      - ./summaries:/home/node/summaries:ro
    networks:
      - wiki_network
    depends_on:
      - wiki-api

  # Redis (캐싱용)
  redis:
    image: redis:7-alpine
    container_name: redis_wiki
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - wiki_network

volumes:
  n8n_data:
    driver: local
  redis_data:
    driver: local

networks:
  wiki_network:
    driver: bridge
